import type { Metadata } from 'next';
import Header from '@/app/components/header';
import Footer from '@/app/components/footer';
import WaIcon from '@/app/components/wa-icon';
import 'bootstrap/dist/css/bootstrap.min.css';
import Navbar from '@/app/components/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Header />
      <body>
        <Navbar />
        {children}
        <WaIcon />
        <Footer />
      </body>
    </html>
  );
}
